config/routes.rb
Rails.application.routes.draw do

  get '/' => "sports#select"

  get '/select' => 'sports#index'
  
  resources :sports do
    resources :teams, only: [:show]
  end

  resources :teams, except: [:show, :index]

  devise_for :users
  resources :active_squads
  resources :students
  resources :coaches
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html




end

app/models/sport.rb
class Sport < ApplicationRecord
  belongs_to :season
  has_many :teams
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  before_action :set_sport, only: [:show, :edit, :update, :destroy]

  # GET /sports
  # GET /sports.json

  def index
    if params[:season] == "both"
      @sports = Sport.all
    elsif params[:season] == "summer"
      @sports = Sport.where(season: Season.find(1))
    elsif params[:season] == "winter"
      @sports = Sport.where(season: Season.find(2))
    elsif params[:season] == nil
      redirect_to '/'
    end
    puts "GOT TO HERE"
    

    # @sports = Sport.all

    # @winter_sports = []
    # @summer_sports = []
   

    # @sports.each do |sport| 
    #   if sport.season[:id] == 2
    #       @winter_sports << sport
    #   elsif
    #      sport.season[:id] == 1
    #       @summer_sports << sport
    #   end
    # end 
    #new variable (@season) when selected 
  end

  def select
  
  end

  # def change_season
  #   if params[:season] == "Summer"
  #     @flag = "Summer"
  #   elsif params[:season] == "Winter"
  #     @flag = "Winter"
  #   end

  #   p params

  #   redirect_to '/sports'

  # end

  # GET /sports/1
  # GET /sports/1.json
  def show
  end

  # GET /sports/new
  def new
    @sport = Sport.new
    authorize(Coach)
  end

  # GET /sports/1/edit
  def edit
    authorize(Coach)
  end

  # POST /sports
  # POST /sports.json
  def create
    @sport = Sport.new(sport_params)

    respond_to do |format|
      if @sport.save
        format.html { redirect_to @sport, notice: 'Sport was successfully created.' }
        format.json { render :show, status: :created, location: @sport }
      else
        format.html { render :new }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sports/1
  # PATCH/PUT /sports/1.json
  def update
    authorize(Coach)
    respond_to do |format|
      if @sport.update(sport_params)
        format.html { redirect_to @sport, notice: 'Sport was successfully updated.' }
        format.json { render :show, status: :ok, location: @sport }
      else
        format.html { render :edit }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # DELETE /sports/1
  # DELETE /sports/1.json
  def destroy
    authorize(Coach)
    @sport.destroy
    respond_to do |format|
      format.html { redirect_to sports_url, notice: 'Sport was successfully destroyed.' }
      format.json { head :no_content }
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sport
      @sport = Sport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sport_params
      params.require(:sport).permit(:name, :season_id, :gender)
    end

end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/sports/_form.html.erb
<%= form_with(model: sport, local: true) do |form| %>
  <% if sport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sport.errors.count, "error") %> prohibited this sport from being saved:</h2>

      <ul>
      <% sport.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :season_id %>
    <%= form.select :season_id, [["Summer", 1],["Winter", 2]]  %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.select :gender, [["Boy", 'Boy'],["Girl", 'Girl']] %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sports/edit.html.erb
<h1>Editing Sport</h1>

<%= render 'form', sport: @sport %>

<%= link_to 'Show', @sport %> |
<%= link_to 'Back', sports_path %>

app/views/sports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>  Sports </h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Season</th>
      <th>Gender</th>
      <th colspan="3"></th>
    </tr>
  </thead>



<% # GOT TO FIND A WAY TO GET SPORT NAME TO DISPLAY AS "#{sport.gender} sport.name" %>
  <tbody>
      <tr>
        <% @sports.each do |sport| %>
        <td><%= sport.name %></td>
        <td><%= sport.season.name %></td>
        <td><%= sport.gender %></td>
        <% if current_user.id == 1 %>
          <td><%= link_to 'Show', sport %></td>
          <td><%= link_to 'Edit', edit_sport_path(sport) %></td>
          <td><%= link_to 'Destroy', sport, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
      <tr>
        
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<% if current_user.id == 1 %>
<%= link_to 'New Sport', new_sport_path %>
<% end %>




  

app/views/sports/new.html.erb
<h1>New Sport</h1>

<%= render 'form', sport: @sport %>

<%= link_to 'Back', sports_path %>

app/views/sports/select.html.erb
<h1> Welcome <h1>

<p> Please select a sport season: </p>


<%= form_with url: '/select', method: :get, local: true do |f| %>
  
  <%= f.select(:season, options_for_select([["Summer", "summer"],["Both", "both"], ["Winter", "winter"]])) %>

  <%= f.submit "Go!" %>

<% end %>

app/views/sports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sport.name %>
</p>

<p>
  <strong>Season:</strong>
  <%= @sport.season[:name] %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @sport.gender %>
</p>

<tbody>
  <% @sport.teams.each do |team| %>
    <tr>
      <td> <%= team.name  %> </td>
      <td><%= link_to 'Show', sport_team_path(team.sport, team) %></td>
      <td><%= link_to 'Edit', edit_team_path(team) %></td>
      <td><%= link_to 'Destroy', team_path(team.sport, team), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
</tbody>

<br>
<br>
<br>

<%= link_to 'Edit', edit_sport_path(@sport) %> |
<%= link_to 'Back', sports_path(@sport.season.id) %>