config/routes.rb
Rails.application.routes.draw do

  get '/' => "sports#select"

  get '/select' => 'sports#index'
  
  resources :sports do
    resources :teams, only: [:show]
  end

  resources :teams, except: [:show, :index]

  devise_for :users
  resources :active_squads
  resources :students
  resources :coaches
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html




end

app/models/active_squad.rb
class ActiveSquad < ApplicationRecord
  belongs_to :team
  belongs_to :student
end

app/controllers/active_squads_controller.rb
class ActiveSquadsController < ApplicationController
  before_action :set_active_squad, only: [:show, :edit, :update, :destroy]

  # GET /active_squads
  # GET /active_squads.json
  def index
    @active_squads = ActiveSquad.all
  end

  # GET /active_squads/1
  # GET /active_squads/1.json
  def show
  end

  # GET /active_squads/new
  def new
    @active_squad = ActiveSquad.new
  end

  # GET /active_squads/1/edit
  def edit
  end

  # POST /active_squads
  # POST /active_squads.json
  def create
    @active_squad = ActiveSquad.new(active_squad_params)

    respond_to do |format|
      if @active_squad.save
        format.html { redirect_to @active_squad, notice: 'Active squad was successfully created.' }
        format.json { render :show, status: :created, location: @active_squad }
      else
        format.html { render :new }
        format.json { render json: @active_squad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /active_squads/1
  # PATCH/PUT /active_squads/1.json
  def update
    respond_to do |format|
      if @active_squad.update(active_squad_params)
        format.html { redirect_to @active_squad, notice: 'Active squad was successfully updated.' }
        format.json { render :show, status: :ok, location: @active_squad }
      else
        format.html { render :edit }
        format.json { render json: @active_squad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /active_squads/1
  # DELETE /active_squads/1.json
  def destroy
    @active_squad.destroy
    respond_to do |format|
      format.html { redirect_to active_squads_url, notice: 'Active squad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_active_squad
      @active_squad = ActiveSquad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def active_squad_params
      params.require(:active_squad).permit(:team_id, :student_id)
    end
end

app/helpers/active_squads_helper.rb
module ActiveSquadsHelper
end

app/views/active_squads/_form.html.erb
<%= form_with(model: active_squad, local: true) do |form| %>
  <% if active_squad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(active_squad.errors.count, "error") %> prohibited this active_squad from being saved:</h2>

      <ul>
      <% active_squad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.text_field :team_id %>
  </div>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.text_field :student_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/active_squads/edit.html.erb
<h1>Editing Active Squad</h1>

<%= render 'form', active_squad: @active_squad %>

<%= link_to 'Show', @active_squad %> |
<%= link_to 'Back', active_squads_path %>

app/views/active_squads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Active Squads</h1>

<table>
  <thead>
    <tr>
      <th>Team</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @active_squads.each do |active_squad| %>
      <tr>
        <td><%= active_squad.team %></td>
        <td><%= active_squad.student %></td>
        <td><%= link_to 'Show', active_squad %></td>
        <td><%= link_to 'Edit', edit_active_squad_path(active_squad) %></td>
        <td><%= link_to 'Destroy', active_squad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Active Squad', new_active_squad_path %>

app/views/active_squads/new.html.erb
<h1>New Active Squad</h1>

<%= render 'form', active_squad: @active_squad %>

<%= link_to 'Back', active_squads_path %>

app/views/active_squads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @active_squad.team %>
</p>

<p>
  <strong>Student:</strong>
  <%= @active_squad.student %>
</p>

<%= link_to 'Edit', edit_active_squad_path(@active_squad) %> |
<%= link_to 'Back', active_squads_path %>